### ISSUE TITLE
More sample .wav file

### ISSUE THREAD

**Issue by jharwinbarrozo** [Xerbo/Lucky7-Decoder#1]
Not really an issue, but for us to test the image decoder - we need 1 or 2 .wav file and not .bin. 
I was able to run your decoder from your example .bin and it indeed resulted an image. 

I wonder if it's possible to provide .wav file that contain data that can decode into an image. I'm looking at gr-satellites satellite-recording, but [this wav file](https://github.com/daniestevez/satellite-recordings/blob/bdbaf02e6416f6be5b01113d9851730bffa6f353/lucky_7.wav) only contains telemetry that can be decoded using gr_satellites. 

Lucky-7 will have good passes in the next few days here in the Philippines, so I could provide one or two.

Thanks

**Comment by Xerbo** [comment]
Ah good idea, I've throw some (the same ones as the current example data) on my Nextcloud, https://cloud.xerbo.net/s/jGFk7WNygFoG54T.

**Comment by Xerbo** [comment]
Oh, and feel free to send me some extra sample data, I would be happy to add it!
